name: Atualizando arquivos
on:
  push:
    branches: master 
  pull_request:
    branches: master 
jobs:
  name: Build
  runs-on: ubuntu-latest
  steps:
  - name: Executando comandos remotos
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      port: ${{ secrets.PORT }}
      script: whoami
