name: Atualizando arquivos

on:
  push:
    branches: master 
  pull_request:
    branches: master 

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Atualizando Servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        envs: |
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
        sync: true
        source: ".env"
        script: |
          cd /var/www/html
          git pull origin master
          composer install  
          
    - name: Reiniciando Supervisor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_ROOT }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        sync: true
        script: |
          sudo systemctl restart supervisord.service
          ${{ secrets.SSH_PASS }}
        
   
      
