name: Atualizando arquivos no servidor

on:
  push:
    branches: master 
  pull_request:
    branches: master 

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        #server-dir: public_html/
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}

    - name: Validate composer.json and composer.lock
      run: composer update 

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Atualizando Servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_ROOT }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        sync: true
        script: |
<<<<<<< HEAD
          cd /var/www/html
          git pull origin master
          composer install
          sudo systemctl restart supervisord.service
          ${{ secrets.SSH_PASS }}  
          
   
          
        
   
      
=======
          systemctl restart supervisord.service
          


>>>>>>> master
